import { linkId, type Link } from '@linkops/domain';

/**
 * Deterministic initial fleet (10 links; assignment requires 8..12).
 *
 * Every field is fixed (ids `link-0001`..`link-0010`, version `1`, a constant
 * baseline timestamp, unique names) so the fleet is identical on every
 * application start — essential for reproducible demos and tests. `txPowerDbm`
 * values stay within the assignment constraint (-10..30). Telemetry generation
 * is out of M1 scope; these links simply have no samples until the M2 simulator
 * runs.
 *
 * Returns fresh objects on each call so callers cannot mutate shared state.
 */
const SEED_TIMESTAMP = '2025-01-01T00:00:00.000Z';

export function createSeedLinks(): Link[] {
  return [
    {
      id: linkId('link-0001'),
      name: 'HQ ↔ North Tower',
      siteA: 'HQ Rooftop',
      siteB: 'North Tower',
      band: '5GHz',
      mode: 'PtP',
      channelWidthMhz: 40,
      capacityMbps: 250,
      txPowerDbm: 20,
      version: 1,
      createdAt: SEED_TIMESTAMP,
      updatedAt: SEED_TIMESTAMP,
    },
    {
      id: linkId('link-0002'),
      name: 'HQ ↔ Harbor Relay',
      siteA: 'HQ Rooftop',
      siteB: 'Harbor Relay',
      band: '6GHz',
      mode: 'PtP',
      channelWidthMhz: 80,
      capacityMbps: 500,
      txPowerDbm: 23,
      version: 1,
      createdAt: SEED_TIMESTAMP,
      updatedAt: SEED_TIMESTAMP,
    },
    {
      id: linkId('link-0003'),
      name: 'Campus Distribution',
      siteA: 'Data Center',
      siteB: 'Campus Hub',
      band: '24GHz',
      mode: 'PtMP',
      channelWidthMhz: 80,
      capacityMbps: 750,
      txPowerDbm: 15,
      version: 1,
      createdAt: SEED_TIMESTAMP,
      updatedAt: SEED_TIMESTAMP,
    },
    {
      id: linkId('link-0004'),
      name: 'Stadium Backhaul',
      siteA: 'Core POP',
      siteB: 'Stadium',
      band: '60GHz',
      mode: 'PtP',
      channelWidthMhz: 160,
      capacityMbps: 1000,
      txPowerDbm: 10,
      version: 1,
      createdAt: SEED_TIMESTAMP,
      updatedAt: SEED_TIMESTAMP,
    },
    {
      id: linkId('link-0005'),
      name: 'Rural Access East',
      siteA: 'Regional POP',
      siteB: 'East Village',
      band: '5GHz',
      mode: 'PtMP',
      channelWidthMhz: 20,
      capacityMbps: 120,
      txPowerDbm: 27,
      version: 1,
      createdAt: SEED_TIMESTAMP,
      updatedAt: SEED_TIMESTAMP,
    },
    {
      id: linkId('link-0006'),
      name: 'Industrial Park Link',
      siteA: 'Metro Ring',
      siteB: 'Industrial Park',
      band: '6GHz',
      mode: 'PtP',
      channelWidthMhz: 40,
      capacityMbps: 300,
      txPowerDbm: 18,
      version: 1,
      createdAt: SEED_TIMESTAMP,
      updatedAt: SEED_TIMESTAMP,
    },
    {
      id: linkId('link-0007'),
      name: 'Airport Perimeter',
      siteA: 'Terminal Roof',
      siteB: 'Cargo Apron',
      band: '24GHz',
      mode: 'PtP',
      channelWidthMhz: 80,
      capacityMbps: 600,
      txPowerDbm: 12,
      version: 1,
      createdAt: SEED_TIMESTAMP,
      updatedAt: SEED_TIMESTAMP,
    },
    {
      id: linkId('link-0008'),
      name: 'Hospital Uplink',
      siteA: 'Central Hospital',
      siteB: 'Metro Ring',
      band: '5GHz',
      mode: 'PtP',
      channelWidthMhz: 40,
      capacityMbps: 200,
      txPowerDbm: 22,
      version: 1,
      createdAt: SEED_TIMESTAMP,
      updatedAt: SEED_TIMESTAMP,
    },
    {
      id: linkId('link-0009'),
      name: 'Warehouse Mesh West',
      siteA: 'Distribution Center',
      siteB: 'West Depot',
      band: '60GHz',
      mode: 'PtMP',
      channelWidthMhz: 160,
      capacityMbps: 900,
      txPowerDbm: 8,
      version: 1,
      createdAt: SEED_TIMESTAMP,
      updatedAt: SEED_TIMESTAMP,
    },
    {
      id: linkId('link-0010'),
      name: 'University Ring North',
      siteA: 'Science Faculty',
      siteB: 'North Campus',
      band: '6GHz',
      mode: 'PtP',
      channelWidthMhz: 80,
      capacityMbps: 450,
      txPowerDbm: 19,
      version: 1,
      createdAt: SEED_TIMESTAMP,
      updatedAt: SEED_TIMESTAMP,
    },
  ];
}
